version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "coursedevapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r3mslu55md06"
s3_prefix = "coursedevapp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
